### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by aknosis** [edumserrano/find-create-or-update-comment#13]
_Corrected_

Currently `v1` is a couple of commits behind `main` which upstream has a fair amount of minor updates.

If the v1 tag could be updated to latest commit, that would be appreciated.

**Comment by edumserrano** [comment]
These are the differences between `v1` and latest `main` as of now: https://github.com/edumserrano/find-create-or-update-comment/compare/v1...main

![image](https://github.com/edumserrano/find-create-or-update-comment/assets/15857357/51ea7cae-b83f-494f-a256-d9cfc808a0e8)

There is only a 3 commit difference:
- two of those commits don't matter to the action at all, they are documentation updates and workflow updates for this GitHub repo.
- the other commit is a dependabot update to [one of the dependencies](https://github.com/edumserrano/find-create-or-update-comment/pull/12) of this composite action. And as you can see [on the list of changes of that dependency update](https://github.com/peter-evans/create-or-update-comment/compare/v3.0.1...v3.0.2), the noticeable difference is a small usability fix to make the action give a better error message in a scenario where you try to update a comment with a body that is too long. 

I will create a new release just to pick up that last usability fix, I just wanted to be clear that you aren't going to gain much with it.

**Comment by edumserrano** [comment]
New release now available: [v1.0.4](https://github.com/edumserrano/find-create-or-update-comment/releases/tag/v1.0.4). The `v1` tag has been updated to now point to latest version as well.

Thank you for your interest in this action.
