### ISSUE TITLE
Release `main` to v2 (or create v3)

### ISSUE THREAD

**Issue by blimmer** [edumserrano/find-create-or-update-comment#18]
It looks like you updated in the transitive dependencies to versions that use Node 20. However, it has been merged to the v2 branch yet.

Could you merge to v2 or create a v3 release if you're worried about breaking compatibility?

Thanks for this great action!

**Comment by edumserrano** [comment]
Fixed by [v3.0.0 release](https://github.com/edumserrano/find-create-or-update-comment/releases/tag/v3.0.0).

**Comment by blimmer** [comment]
Thank you!
