### ISSUE TITLE
Markdown template support

### ISSUE THREAD

**Issue by stovmascript** [edumserrano/find-create-or-update-comment#2]
Would it be possible to forward [template inputs](https://github.com/peter-evans/create-or-update-comment#using-a-markdown-template)?

Looks like these inputs are not documented in the [action inputs table](https://github.com/peter-evans/create-or-update-comment#action-inputs), making them easy to miss.

**Comment by edumserrano** [comment]
Perhaps I'm misunderstanding but you can already use templating *in combination* with this action. 

The actions itself, this one or the ones from Peter Evans on which this one is built, **do not support** any kind of templating.  What Peter explains in the [Using a markdown template section](https://github.com/peter-evans/create-or-update-comment#using-a-markdown-template) is that you can use another action to apply the template you want and then you use the templated output as an input on the `body` action input parameter of `peter-evans/create-or-update-comment@v2`. 

You could do the same and use this action. Meaning you would use whatever templating action you want to produce your templated output and then pass it into the `body` action input parameter of this action.

**Comment by edumserrano** [comment]
Closing this issue since the request is out of scope for this action. The provided instructions in my previous comment would let you accomplish what you want.
